
const sea = "A dreamy sea has a rhythmic pulse to it unmatched by any other part of nature. It forges its own sounds and kindles its own symphony. The following 25 sentences are an attempt to capture the song of the sea and its steady, throbbing heartbeat. If you find yourself visualising its glorious vastness, its dreamy surface and straining to hear its metronomic wave music, you may understand why it’s called the fisherman’s friend."
const sky ='How can I describe a beautiful sky?It is monumental. It is violent, calm, serene, and loud, changing shapes and ever-present. The sky is a vast, endless, and ever-changing canvas of colors. Its a place where the sun sets and the moon rises'
const leaf = "leaf, in botany, any usually flattened green outgrowth from the stem of a vascular plant. As the primary sites of photosynthesis, leaves manufacture food for plants, which in turn ultimately nourish and sustain all land animals. Botanically, leaves are an integral part of the stem system."
const avanue = "Avenue trees and shrubs line our streets, decorate our squares and provide valuable green features in our cities, towns and villages. Often planted in lines, avenue trees and shrubs are usually of the same species or cultivar to give streets or parks a uniform perspective."
const cars = "Cars have controls for driving, parking, passenger comfort, and a variety of lights. Over the decades, additional features and controls have been added to vehicles, making them progressively more complex. These include rear-reversing cameras, air conditioning, navigation systems, and in-car entertainment. Most cars in use in the early 2020s are propelled by an internal combustion engine, fuelled by the combustion of fossil fuels. Electric cars, which were invented early in the history of the car, became commercially available in the 2000s and are predicted to cost less to buy than gasoline cars before 2025.[5][6] The transition from fossil fuels to electric cars features prominently in most climate change mitigation scenarios,[7] such as Project Drawdown's 100 actionable solutions for climate change"
const snow = "All I could feel on my tender, fragile skin was frezzing cold air , I wish I would of warn my huge, soft, and comfortable snow jaket. The sound of silence around me was chilling and frighting, in every posible way. Then I herd a crackle and a snap in the forest around me and I started running, in a few seconds I realized it was me that steped on a delicate frostbitten tree branch. After I settled down, I noticed I lost my way back to my cabin on Purden Mountain. I saw something very faint in the distance, after I made it closer to were it was I saw it"
const code = "A Simple Definition. Coding is the process of transforming ideas, solutions, and instructions into the language that the computer can understand – that is, binary-machine code. Coding is how humans are able to talk with computers."


export {sea, sky, leaf, avanue, cars, snow, code}